layout_spectrum: 0.648436656454578
typography_spectrum: 0.6083881841041148
color:
  brandStrength: 0.3130664217751473
  lightness: 0.7216656398959458
  saturation: 0.6957783168181777
  rhythmicContrast: 0.9363893237896264
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
name: Conciencia de Habitar
navigation:
  - name: ADN
    id: 2c3574b6-b469-4ea8-9a17-7dc0ffe0f6fe
    type: content
